apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv1-claim
  labels:
    app: mongodb
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
